version: '3.7'
services:
 dynamodb-local:
   image: amazon/dynamodb-local:latest
   container_name: dynamodb-local
   networks:
      - backend
   ports:
    - "8000:8000"

networks:
  backend:
    name: lambda-local
