AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-meetup
  Sample SAM Template for aws-meetup

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
      Runtime: go1.x
      Timeout: 5
Resources:
  FileAnalyzerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: file-analyzer/
      Handler: file-analyzer
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref FileMetadata
      Events:
        UploadEvent:
          Type: S3
          Properties:
            Bucket: !Ref ServerlessMeetup
            Events: s3:ObjectCreated:*
  GetFilesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-files/
      Handler: get-files
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref FileMetadata
      Events:
        CatchAll:
          Type: Api
          Properties:
            Method: GET
            Path: /files
  ServerlessMeetup:
    Type: AWS::S3::Bucket

  FileMetadata:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: FileMetadata
      PrimaryKey:
        Name: Key
        Type: String

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  API:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  FileAnalyzerFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt FileAnalyzerFunction.Arn
  MeetupBucket:
    Value: !Ref ServerlessMeetup
    Description: URL for website hosted on S3
